name: pyeit-environment
channels:
  - defaults
  - conda-forge
dependencies:
  - pytest
  - pytest-cov
  - "numpy>=1.20"
  - scipy
  - pandas
  - matplotlib-base
  - vispy
  - shapely
  - trimesh
  - "imageio>=2.19"
  - allantools